### ISSUE TITLE
Spell Slot Tracking

### ISSUE THREAD

**Issue by Paul-Ladyman** [Paul-Ladyman/dnd-battle-tracker#517]
Requested by DM Cam via Ko-Fi

**Comment by Paul-Ladyman** [comment]
With the API data that comes with selecting a creature from the dropdown menu in the Create Creature Menu, a creature's total spell slots could be displayed alongside the used spell slots.

**Comment by Paul-Ladyman** [comment]
Spell slots are probably not something to share with players by default.

**Comment by vforvasile** [comment]
Hey Paul!

I've worked a bit on this, it's WIP for now.

Take a look: [PR](https://github.com/vforvasile/dnd-battle-tracker/pull/2)

I'm too lazy to recreate this with another PR to sync with your branch since I'm quite behind and have changes with creature stats and armor class, autoscroll etc. (Also I use a lot of div onClicks because I don't want to override button styling 🤷🏾 )

You could use it as inspiration. 🤓

**Comment by Paul-Ladyman** [comment]
Hi Vasile!

Yeah nice. I had imagined a similar interface so it's great to see what that looks like for real, this will definitely be super useful :+1: .
