### ISSUE TITLE
Saved Creatures Don't Show Initiative Field on Battle Reset

### ISSUE THREAD

**Issue by Adkaiser** [Paul-Ladyman/dnd-battle-tracker#525]
When you reset a battle with locked creatures, those creatures don't show their initiative input field anymore. It looks like this is because the initiative field only displays when initiative is 'null' now, but reset still sets initiative to 'undefined'. Because of this, saved creatures can't be given new initiatives and the battle can't be started.

**Comment by Paul-Ladyman** [comment]
Great spot @Adkaiser thanks! This should now be fixed in v5.25.4, which has been deployed to the live site. It might take a little while to make it through the cache but if you find some time to double check things look OK I'd really appreciate it.

Looks like I introduced a couple of bugs since adding support for dice notation for the initiative field where I've started using `null` to represent no initiative instead of `undefined` as you say (classic bug). For now I've just supported both values in the logic to display the initiative tool to fix the bug but I should come back later and make things consistent and more importantly add some tests!

Anyway that's just me thinking out loud. Thanks again for the bug report, hope it didn't mess your game up too much!

**Comment by Adkaiser** [comment]
No problem, as you say, it's a classic bug. It looks like it is fixed now - I see the fields show up, can enter initiative value, and combatants get resorted when the new battle is started. The only thing I noticed is that it doesn't look like dice notation works in the creature toolbar initiative field, and to be fair, I never tested to see if it does or should.

**Comment by Paul-Ladyman** [comment]
That's great thanks again @Adkaiser, I'll close this issue now.

Regarding the dice notation your observation is correct, the only field that supports this so far is the initiative field in the create creature form. Ultimately I'm planning to allow dice notation in any number field, plus a specific input just for rolling dice.
